Ghc 8.8
scrive/unjson pull request #18
Opened 2020-03-30 16:33 UTC by Siprj

2020-04-01 12:42 UTC, arybczak requested changes

2020-04-01 12:42 UTC, arybczak commented on src/Data/Unjson.hs
> +renderForPath :: (MonadFail m, Monad m) => Path -> UnjsonDef a -> m String
Isn't Monad redundant here? Same for below changes.

2020-04-01 12:42 UTC, arybczak commented on unjson.cabal
> +tested-with:         GHC == 8.0.2, GHC == 8.2.2, GHC == 8.4.4, GHC == 8.6.5,
Can you make it have the same format as hpqtypes?

2020-04-01 12:42 UTC, arybczak commented on unjson.cabal
> +  build-depends:       base >= 4.7 && < 4.15,
`4.9` has to be the lower bound.

2020-04-01 12:42 UTC, arybczak commented on test/Test.hs
> +        "parsing Integer failed, expected Number, but encountered String"
Ah, I see old messages were inaccurate, nice.

2020-04-02 13:26 UTC, arybczak approved these changes
LGTM :+1: :tada:

2020-04-02 13:30 UTC, arybczak commented
Before merging you can also update `lts` in `stack.yml` (it's part of #17) so that we can close both #17  and #15 as as far as I see this PR includes both changes.

2020-04-03 08:49 UTC, merged

2020-05-06 10:00 UTC, soareschen commented
@arybczak has this been published to Hackage?

2020-05-06 10:09 UTC, arybczak commented
It was now.